[package]
name = "agent"
version = "0.1.0"
edition = "2024"  

[dependencies]
hostname = "0.3"
anyhow = "1.0.98"
dotenvy = "0.15.7"
envy = "0.4.2"
nix = { version = "0.30.1", default-features = false, features = ["inotify", "fs"] }
postgres = "0.19.10"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
uuid = "1.17.0"
config = { version = "0.15", features = ["toml", "json"] }
