[package]
name = "crystal-forge"
version = "0.1.47"
edition = "2024"  

[dependencies]
hostname = "0.3"
anyhow = "1.0.98"
dotenvy = "0.15.7"
envy = "0.4.2"
sysinfo = "0.34.2"
nix = { version = "0.30.1", default-features = false, features = ["inotify", "fs" ,"user"] }
postgres = "0.19.10"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
config = { version = "0.15", features = ["toml", "json"] }
tempfile = "3.20.0"
tokio = { version = "1.37", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
axum = "0.7"
hyper = { version = "1", features = ["full"] }
serde_json = "1"
tokio-postgres = { version = "0.7.13", features = ["runtime", "with-uuid-1"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.8"
base64 = "0.21"
reqwest = { version = "0.11", features = ["json","blocking", "rustls-tls"] }
sha2 = "0.10.9"
systemstat = "0.2.4"
futures = "0.3.31"
bigdecimal = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.8.6", features = ["uuid", "postgres", "runtime-tokio", "chrono", "macros", "bigdecimal"] }
chrono = { version = "0.4.41", features = ["serde"] }
watch = "0.2.3"
clap = { version = "4.0", features = ["derive"] }
tokio-test = "0.4.4"
axum-test = "17.3.0"
winnow = "0.7.11"
bytes = "1.10.1"
humantime-serde = "1.1.1"

[lib]
path = "src/lib.rs"

[[bin]]
name = "agent"
path = "src/bin/agent.rs"

[[bin]]
name = "test-agent"
path = "src/bin/test-agent.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "builder"
path = "src/bin/builder.rs"

[[bin]]
name = "cf-keygen"
path = "src/bin/cf-keygen.rs"

[package.metadata.sqlx]
offline = true
