[package]
name = "crystal-forge"
version = "0.1.0"
edition = "2024"  

[dependencies]
hostname = "0.3"
anyhow = "1.0.98"
dotenvy = "0.15.7"
envy = "0.4.2"
nix = { version = "0.30.1", default-features = false, features = ["inotify", "fs"] }
postgres = "0.19.10"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
uuid = "1.17.0"
config = { version = "0.15", features = ["toml", "json"] }
tempfile = "3.20.0"
tokio = { version = "1.37", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
axum = "0.7"
hyper = { version = "1", features = ["full"] }
serde_json = "1"
tokio-postgres = { version = "0.7.13", features = ["runtime", "with-uuid-1"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.8"
base64 = "0.21"

[lib]
path = "src/lib.rs"

[[bin]]
name = "agent"
path = "src/bin/agent.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "cf-keygen"
path = "src/bin/cf-keygen.rs"

