[database]
host = "reckless"
user = "crystal_forge"
password = "password"
dbname = "crystal_forge"

[server]
host = "0.0.0.0"
port = 3000

[server.authorized_keys]
gray = "hUwxCZUFydwDjf8BMyXLyMiI33PrKvhfDRj60OkisdY="

[client]
server_host = "localhost"
server_port = 3000
private_key = "/var/lib/crystal_forge/gray.key"
