[database]
host = "reckless"
user = "crystal_forge"
password = "1password"
dbname = "crystal_forge"

[server]
host = "0.0.0.0"
port = 3000
authorized_keys = "/var/lib/crystal_forge/authorized_keys"

[client]
server_host = "daly"
server_port = 3000
private_key = "/var/lib/crystal_forge/client_key.pem"
