[database]
host = "reckless"
user = "crystal_forge"
password = "password"
dbname = "crystal_forge"

[server]
host = "0.0.0.0"
port = 3000

[server.authorized_keys]
gray = "hUwxCZUFydwDjf8BMyXLyMiI33PrKvhfDRj60OkisdY="
reckless = "SKYgYiwK0vMwK3sJP6R53z0gbtOVSWOmJ33WT4AbCQ8="

[client]
server_host = "reckless"
server_port = 3944
private_key = "/var/lib/crystal_forge/gray.key"
