[database]
host = "reckless"
user = "crystal_forge"
password = "password"
name = "crystal_forge"

[server]
host = "0.0.0.0"
port = 3000

[client]
server_host = "reckless"
server_port = 3000
private_key = "/var/lib/crystal_forge/gray.key"

[flakes.watched]
dotfiles = "git+https://gitlab.com/usmcamp0811/dotfiles"

[environments]
name = "dev"
description = "Development environment for Crystal Forge agents and evaluation"
is_active = true
risk_profile = "LOW"
compliance_level = "NONE"

[[systems]]
hostname = "gray"
public_key = "hUwxCZUFydwDjf8BMyXLyMiI33PrKvhfDRj60OkisdY="
environment = "dev"

[[systems]]
hostname = "reckless"
public_key = "SKYgYiwK0vMwK3sJP6R53z0gbtOVSWOmJ33WT4AbCQ8="
environment = "dev"

[[systems]]
hostname = "butler"
public_key = "AbCDEfGhIJklMNOpQRstUvWxYZ0123456789abcdefg="
environment = "test"
