[database]
host = "reckless"
user = "crystal_forge"
password = "password"
dbname = "crystal_forge"

[server]
host = "0.0.0.0"
port = 3000
authorized_keys = [
  "hUwxCZUFydwDjf8BMyXLyMiI33PrKvhfDRj60OkisdY=", # gray
]

[client]
server_host = "reckless"
server_port = 3000
private_key = "/var/lib/crystal_forge/gray.key"
